# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 17:10
from __future__ import unicode_literals

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0002_auto_20161225_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', users.managers.RoleUserManager()),
            ],
        ),
    ]
