# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 22:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import djroles.roles


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0005_auto_20161226_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Officer',
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='position')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', djroles.roles.BaseRole),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
