# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20161226_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officer',
            options={},
        ),
        migrations.AlterModelManagers(
            name='officer',
            managers=[
            ],
        ),
    ]
