# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0003_auto_20160715_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='cost')),
                ('minutes', models.IntegerField(verbose_name='minutes')),
                ('duration', models.IntegerField(blank=True, verbose_name='duration')),
                ('minute_billing', models.BooleanField(default=True, verbose_name='minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.Event')),
            ],
            bases=('schedule.event',),
        ),
        migrations.CreateModel(
            name='ScheduleCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charges.Charge')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charges.Schedule')),
            ],
            options={
                'ordering': ('schedule', 'order'),
            },
        ),
        migrations.CreateModel(
            name='ScheduleLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nazwa')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='charges',
            field=models.ManyToManyField(through='charges.ScheduleCharge', to='charges.Charge'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charges.ScheduleLot', verbose_name='schedule lot'),
        ),
    ]
