# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='duration',
            field=models.IntegerField(blank=True, verbose_name='duration'),
        ),
    ]
