# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='opis'),
        ),
    ]
