# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('plate_country', django_countries.fields.CountryField(default='PL', max_length=2, verbose_name='Plate country')),
                ('plate_number', models.CharField(max_length=20, verbose_name='Plate number')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Vehicle's owner")),
            ],
        ),
    ]
