# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_assigned', models.BooleanField(default=False, help_text='Default is False. True after assigment to vehicle', verbose_name='is assigned')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('plate_country', django_countries.fields.CountryField(default='PL', editable=False, max_length=2, verbose_name='Plate country')),
                ('plate_number', models.CharField(editable=False, max_length=20, verbose_name='Plate number')),
                ('badge', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='badges.Badge', verbose_name='badge')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Vehicle's owner")),
            ],
        ),
    ]
