# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='is_assigned',
        ),
    ]
